### PR TITLE
Doesn't support webpack

### PR DESCRIPTION
**Pull request by Dorian**
Failed to minify the code from this file:

 	./node_modules/query-string/index.js:8

Read more here: http://bit.ly/2tRViJ9

--------

I couldn't post an issue, so I make a pull request instead

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's the inverse, actually. It's Create React App that doesn't support the ecosystem. Use `npm install query-string@5` if you use CRA. Sorry for the trouble, but this is all on CRA which has refused to co-operate with the community and just tells users to annoy maintainers.

> I couldn't post an issue, so I make a pull request instead

The issue tracker is disabled exactly because of issues like this.

**Comment by Dorian** [comment]
No problem, thanks for the answer.

For anyone reading this in the future, I replaced the `query-string` package by this function in `src/query-string.js`:

```
export default {
  parse: function parse(queryString) {
    var query = {};
    var pairs = (queryString[0] === '?' ? queryString.substr(1) : queryString).split('&');
    for (var i = 0; i < pairs.length; i++) {
        var pair = pairs[i].split('=');
        query[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1] || '');
    }
    return query;
  }
}
```

**Comment by jayantbh** [comment]
This https://github.com/sindresorhus/query-string/pull/148#issuecomment-399656020 should actually be added to the README.md. I imagine it would be a fairly common problem.

**Comment by slorber** [comment]
@sindresorhus what should the CRA community do about this error exactly? I've had it also on a non-CRA project (actually, Ruby/Webpacker env) on which I control webpack settings, so wonder what's your advise on how to keep up to date with this package?

Adding config to transpile this module seems a bit annoying so I'm sticking to 5.x for now, just wondering what are the alternatives

**Comment by slipo** [comment]
Agree with @jayantbh. PR https://github.com/sindresorhus/query-string/pull/156 created.

**Pull request closed without merging**
