### PR TITLE
:arrow_up: ava@0.14.0

### PR DESCRIPTION
**Pull request by SamVerschueren**
bumped AVA

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Apparently `Object.create(null).__proto__` returns `null` on node 0.10 and `undefined` on node 0.12+.

**Comment by sindresorhus** [comment]
Weird, just use `t.true(Object.create(null).__proto__ == null)` with a comment then.

**Comment by SamVerschueren** [comment]
It's this test that's failing

```js
t.is(fn.parse('__proto__=bar').__proto__, 'bar');
```

This returns `[null, 'bar']` on node 0.10 which is really an edge case. So I can drop the test if you want.

**Comment by sindresorhus** [comment]
Yeah, drop it.

**Comment by SamVerschueren** [comment]
Done. Don't think it needs other tweaks?

**Comment by sindresorhus** [comment]
:+1: :fireworks:

**Pull request merged**
