### PR TITLE
set default arrayFormat

### PR DESCRIPTION
**Pull request by zhangciwu**
Add the ability to set an arrayFormat as global default setting
convenient for all same setting in one project.

like `jQuery.ajaxSetup()`

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is a very bad idea. It would also affect any usage elsewhere in the dependency tree. Would be better to add support for creating an instance: `queryString.create({encodeOptions: …, decodeOptions: …})`, but not sure it's worth the bloat.

**Comment by zhangciwu** [comment]
@sindresorhus It is an issue that affecting other libs.
But maybe it's what I want, especially that libs not caring about this setting. (just give no option when they use query-string)

Maybe add a description to make lib writer pass option if they intend to not be affected by user default. (which shall be done if they have use other than `none`)

**Comment by sindresorhus** [comment]
I'm not going to add a bad solution even with good docs.

**Comment by zhangciwu** [comment]
Agree, let me think if there is a better solution

**Pull request closed without merging**
