### PR TITLE
Undefined values are removed from stringified output

### PR DESCRIPTION
**Pull request by tlhunter**
When stringifying an object where a value is undefined, previously the value would be passed along as `'undefined'`. Now we remove it from the resulting query string entirely. This makes `qs.stringify()` more consistent with `JSON.stringify()`.

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is inconsistent with the Node.js `querystring` module though.

```
❯ node
> querystring.stringify({abc: undefined, foo: 'baz'})
'abc=&foo=baz'
```

Not really sure which one is correct. What do other query string modules do? Like https://github.com/hapijs/qs

**Comment by tlhunter** [comment]
Hapi's qs library does omit undefined:

https://github.com/hapijs/qs/blob/master/test/stringify.js#L169

**Comment by SamVerschueren** [comment]
I guess @tlhunter is right. I dived into the code (didn't tested it) but it seems that `qs.parse('?val=undefined');` will result in `{val: 'undefined'}`. Couldn't find a test for this so not 100% sure though.

So option 1 is omit the property, option 2 is letting stringify only omit the value but not the key. `qs.stringify({foo: undefined, bar: 1});` will result in `?foo&bar=1`.

**Comment by SamVerschueren** [comment]
I checked it with the following small example

```js
'use strict';

var qs = require('query-string');

console.log(qs.parse(qs.stringify({foo: undefined, bar: 1})));
```

The output is
```
{ bar: '1', foo: 'undefined' }
```

Which is not entirely correct off course.

**Comment by sindresorhus** [comment]
The questions is, is there any value in the result of stringify then parse being identical to the input?

```js
test(t => {
	var x = {foo: undefined};
	t.same(fn.parse(fn.stringify(x)), x);
	t.end();
});
```

**Comment by sindresorhus** [comment]
Maybe `undefined` should be missing key & value and `null` should be missing value? That would be compatible with this check: https://github.com/sindresorhus/query-string/blob/8c6908ed370963cb76f2d9f874b8f370dbc27987/index.js#L28

**Comment by SamVerschueren** [comment]
Seems good!

**Comment by SamVerschueren** [comment]
@tlhunter Care to give it a go? The implementation should be

```js
if (val === undefined) {
	return '';
}
if (val === null) {
	return key;
}
```

+ extra tests

**Comment by tlhunter** [comment]
I'll give it a go

**Comment by sindresorhus** [comment]
@tlhunter Can you fix the merge conflict?

**Comment by tlhunter** [comment]
@sindresorhus fixed

**Pull request closed without merging**
