### PR TITLE
support object properties - fixes #47

### LINKED ISSUE #47: `require('query-string').parse('hasOwnProperty&hasOwnProperty');` breaks
Unsafe usage of `hasOwnProperty` means that parsing certain query strings will throw an error.

The following cases are also not working correctly:

    qs.parse('__proto__');
    qs.parse('__proto__&__proto__');

`Object.create(null)` should fix the problem.

### PR DESCRIPTION
**Pull request by SamVerschueren**
Fixes #47 and ends the discussion in #50. Should be released as breaking change (e.g. `4.x`). Added some improvements over the previous PR regarding this issue and added a note in the documentation. Feel free to provide any feedback :).

// @cspotcode

### CODE REVIEW

**Comment by cspotcode** [comment]
Thanks!  There's a small regression with these two test cases:

```
queryString.parse('a&a'); // should be {a: [null, null]} but returns {a: null}
queryString.parse('a=&a'); // should be {a: ['', null] but returns {a: null}
```

This was caused by replacing the `hasOwnProperty` check with a truthiness check.  Both `null` and the empty string are falsy values.

**Comment by SamVerschueren** [comment]
Good catch! Will fix asap!

**Comment by SamVerschueren** [comment]
Should be fixed.

**Comment by cspotcode** [comment]
Sweet, looks good to me.

**Comment by SamVerschueren** [comment]
Thanks Sindre :+1:!

**Comment by sindresorhus** [comment]
Thanks for the PR :)

**Pull request closed without merging**
