### PR TITLE
Add readme note about `create-react-app`

### PR DESCRIPTION
**Pull request by slipo**
It's confusing if you're using create-react-app and trying to add query-string in. [As jayantbh mentioned](https://github.com/sindresorhus/query-string/pull/148#issuecomment-411693303) we should note this in the README with the known solution.

### CODE REVIEW

**Comment by psyanite** [comment]
I was running 6.1.0, have downgraded to 5 something and is building perfectly now.

**Comment by jamesplease** [comment]
More broadly, @sindresorhus , would you be open to reverting commit  597f14a1c39b16d4b879c3834b006884782c851b ?

I don't think that the value that it provides offsets the troubles that it adds when trying to consume the library. Consumers don't care whether this uses `const` or `var` under the hood – they just want something that works. And, right now, the latest version doesn't work for a lot of people, and that is what they get when they run `npm i query-string`.

For me, any time that I start a new project, I find myself installing v6 (because that's what from `npm i query-string`), getting confused for a moment when my build system explodes, then remembering that I need _v5_, and finally switching over.

Alrigh, so maybe that's not a big deal. I install v5, and then I'm good, right? Not quite, as I get warnings that my dependencies are out of date for the _entire lifetime_ of the project.

**Comment by sindresorhus** [comment]
> More broadly, @sindresorhus , would you be open to reverting commit 597f14a ?

No, sorry.

**Comment by sindresorhus** [comment]
[Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html) supports transpilation of dependencies, so this will not be a problem for much longer.

**Pull request merged**
