### PR TITLE
Split query params using a regex

### PR DESCRIPTION
**Pull request by steveluscher**
Saves an array (`shift`) and a string (`join`) manipulation.

### CODE REVIEW

**Comment by steveluscher** [comment]
One moment please.

**Comment by steveluscher** [comment]
That should do it.

Note: This will probably make this library fail on IE8, if you care.

**Comment by sindresorhus** [comment]
> This will probably make this library fail on IE8, if you care.

I don't, but removing support now would be a breaking change and for little gain. Why would it not work in IE8?

**Comment by steveluscher** [comment]
Just fired up IE8 to try it out:

screen shot 2015-10-10 at 1 09 06 am

**Comment by SamVerschueren** [comment]
What about splitting with indexOf?

**Comment by steveluscher** [comment]
Yep! Could do that.

**Comment by sindresorhus** [comment]
ping @steveluscher

**Pull request closed without merging**
